networks:
  test:
    name: fabric_test
services:
  couchdb1:
    container_name: couchdb${PEER_NUMBER}
    environment:
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.3.2
    labels:
      service: hyperledger-fabric
    networks:
    - test
    ports:
    - ${COUCHDB_PORT}:5984
  peer1.docorg.doctor.com:
    depends_on:
    - couchdb${PEER_NUMBER}
    environment:
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb${PEER_NUMBER}:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
version: '3.7'
