networks:
  test:
    name: fabric_test
services:
  

  orderer.doctor.com:
    command: orderer
    container_name: orderer.doctor.com
    environment:
    - FABRIC_LOGGING_SPEC=INFO
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_LISTENPORT=7050
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
    - ORDERER_CHANNELPARTICIPATION_ENABLED=true
    - ORDERER_ADMIN_TLS_ENABLED=true
    - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
    - ORDERER_OPERATIONS_LISTENADDRESS=orderer.doctor.com:9443
    - ORDERER_METRICS_PROVIDER=prometheus
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    networks:
    - test
    ports:
    - 7050:7050
    - 7053:7053
    - 9443:9443
    volumes:
    - ../organizations/ordererOrganizations/doctor.com/orderers/orderer.doctor.com/msp:/var/hyperledger/orderer/msp
    - ../organizations/ordererOrganizations/doctor.com/orderers/orderer.doctor.com/tls/:/var/hyperledger/orderer/tls
    - orderer.doctor.com:/var/hyperledger/production/orderer
    working_dir: /root
  
volumes:
  orderer.doctor.com: null

  
